package defs

type (
	EntityDefID    string
	CharacterDefID string
	UniquePlayerID string
)

const (
	// This is used to identify the player's state and def. It is the only CharacterDefID that should be defined in the engine.
	PlayerID CharacterDefID = "player"
)

// CharacterDef represents a definition of a single character, and how that character starts off in the world when first introduced.
// Note: it is NOT Character State
type CharacterDef struct {
	// used for identifying the character within places like the DataManager.
	ID CharacterDefID
	// A unique ID for this player, that is unique across playthroughs. allows a specific player's save files to be correctly identified.
	// we can't use display names for this, since more than one character/playthrough might have the same display name.
	// This should not be defined for non-player characters.
	UniquePlayerID UniquePlayerID
	// if true, this character can only be instantiated once at any given time. this enables its characterState to be found by CharacterDefID,
	// since it means we can use CharacterDefID directly without needing to add random strings to it.
	// A non-unique character will have a CharacterStateID that uses CharacterDefID as its base, with randomized string attached at the end.
	Unique      bool
	BodyDef     BodyDef
	DisplayName string // REQ: the main name this character uses. Somewhat short so it can be used everywhere. Ex: "Scipio Africanus".
	FullName    string // OPT: a longer version of the name. Ex: Roman elites will have multiple names, like "Publius Cornelius Scipio Africanus".

	// REQ: the "class" of this character. Usually describes what type of person they are, their combat style, or whatever is most notable.
	// This is set by the classDef, but the classDef remains as is; this just allows a character to have a customized name, but still use a specific base classDef.
	ClassName        string
	ClassDefID       ClassDefID // the actual class def
	CultureID        CultureID
	InitialInventory StandardInventory

	DialogProfileID  DialogProfileID
	FootstepSFXDefID FootstepSFXDefID
	ScheduleID       ScheduleID

	BaseAttributes map[AttributeID]int // Base attribute levels (not including modifiers from traits, etc)
	BaseSkills     map[SkillID]int     // Base skill levels (not including modifiers from traits, etc)
	InitialTraits  []TraitID
	BaseVitals     Vitals // TODO: delete this, since base vitals are determined by attributes
}

// A CharacterGenerator is a definition of a "type" of character to generate in the game world.
// These are associated with a bed in the game (in a Tiled map), and therefore characters generated by this generator know which bed is theirs.
// It is only used for dynamically generated characters; unique characters will have their character def ID directly set in a bed object (in Tiled).
type CharacterGenerator struct {
	ID              string
	CharacterDefIDs []CharacterDefID // list of character defs that can be used when generating this character.
	NameGenFn       func() string    // a function that returns a name that the character will use for its name.
	// list of dialog profiles that can be assigned to a character when generated. If nothing set here, defaults to the one in the character def.
	// the reason we allow multiple is, it allows for some generated characters to have different "attitudes" perhaps. e.g. a friendly town guard vs a grumpy one.
	DialogProfileIDs []DialogProfileID
	// schedule assigned to the generated character. Only one option can be set here, so each unique schedule should have its own character generator.
	// the idea here is, a given bed probably should correspond to a specific type of character that performs a specific role in the game world.
	// If none is set, the one set in the character def is used.
	ScheduleID ScheduleID
}

func (cg CharacterGenerator) Validate() {
	if cg.ID == "" {
		panic("id was empty")
	}
	if len(cg.CharacterDefIDs) == 0 {
		panic("no character def IDs set")
	}
}
